// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHD0WwNLtwdR4Vg-Sa8ojsvSuOzG3d2xE',
    appId: '1:520960204746:web:adfd8f3516ac6d0e36b933',
    messagingSenderId: '520960204746',
    projectId: 'nizwaapp-f2511',
    authDomain: 'nizwaapp-f2511.firebaseapp.com',
    storageBucket: 'nizwaapp-f2511.appspot.com',
    measurementId: 'G-LRZG1B1PZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo78ZMYzUUg57froqJ4_GrE7WDSyLfuNs',
    appId: '1:520960204746:android:17a0ede7d6a774de36b933',
    messagingSenderId: '520960204746',
    projectId: 'nizwaapp-f2511',
    storageBucket: 'nizwaapp-f2511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9YK3NoHAq83XRtaGTZ5p2qQnz1Ne0vuc',
    appId: '1:520960204746:ios:19e0670eb07a59c536b933',
    messagingSenderId: '520960204746',
    projectId: 'nizwaapp-f2511',
    storageBucket: 'nizwaapp-f2511.appspot.com',
    iosBundleId: 'com.example.nizwaTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9YK3NoHAq83XRtaGTZ5p2qQnz1Ne0vuc',
    appId: '1:520960204746:ios:4104d1703693061136b933',
    messagingSenderId: '520960204746',
    projectId: 'nizwaapp-f2511',
    storageBucket: 'nizwaapp-f2511.appspot.com',
    iosBundleId: 'com.example.nizwaTest.RunnerTests',
  );
}
